#:schema node_modules/wrangler/config-schema.json
name = "smail"
compatibility_date = "2024-09-25"
main = "app/worker.ts"
assets = { directory = "./build/client" }

[observability]
enabled = true

[[kv_namespaces]]
binding = "KV"
id = "63c9a37d9aad44dc8f170c12bc3fa52d"

[[d1_databases]]
binding = "DB"
database_name = "smail"
database_id = "058bb3f9-5dc4-4f00-8426-a24c9cd95de4"
preview_database_id = "058bb3f9-5dc4-4f00-8426-a24c9cd95de4"
migrations_dir = "app/drizzle"
